### ISSUE TITLE
배송 카드 삭제 버튼이 보이지 않습니다.

### ISSUE THREAD

**Issue by HyeAnn-Lee** [parcel-tracking/extension-for-whale#40]
현재 사진 첨부드립니다.
Windows입니다.
일반모드에서 X 버튼이 보이지 않네요. 다크모드에서는 잘 보입니다. 일반모드에서도 X 위치에 마우스 호버 시 삭제할 수 있긴 해서, 단순히 버튼만 안 보이는 문제 같습니다. 버튼이 하얀색인 걸까요?
v1.8.3 에서는 X 버튼이 잘 보였던 것 같습니다.

![image](https://github.com/user-attachments/assets/c0fa16f0-12fb-459b-8a68-35d996364356)

![image](https://github.com/user-attachments/assets/1b8adbbc-739c-4790-93e3-c23e46e11eb1)

**Comment by falsy** [comment]
@HyeAnn-Lee 앗?!.. 
다크 모드 스타일을 수정하는 과정에서 미디어 쿼리가 생략되어서 라이트 모드에서도 흰색으로 출력되서 보이지 않았네요..
이렇게 직접 이슈로 바로 알려주셔서 감사합니다!! 😀
